development:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  channel_prefix: harvey-api_development

test:
  adapter: redis
  url: redis://127.0.0.1:6379/2
  channel_prefix: harvey-api_test

production:
  adapter: redis
  url: ENV["REDIS_URL"]
  channel_prefix: harvey-api_production
