default: &default
  categories:
    - labor:
      - muck:
      - trash:
      - clean:
      - shop:
      - laundry:
      - cook:
      - sit:
      - specialized:
        - medical
        - home_repair
        - electrician
        - legal
        - pest_control
        - counselor
        - other_specialized
      - other_labor:
    - equipment:
      - construction
      - power_tools
      - tools
      - water_pump
      - protective_gear
      - generator
      - dehumidifier
      - appliances
      - other_equipment
    - supplies:
      - construction
      - home_repair
      - cleaning_supplies
      - household_items
      - personal_care
      - baby_and_child_care
      - clothes
      - medicine
      - furniture
      - fuel
      - other_supplies
    - transportation:
      - pickup_truck
      - bus_or_van
      - tow_truck
      - boat_motor
      - boat_no_motor
      - other_transportation
    - housing:
      - number_of_adults: 0
      - number_of_children: 0
      - number_of_pets:
                    - dog
                    - cat
                    - other
    - food:
      - ready_to_eat
      - baby_formula
      - drinking_water
      - canned_food
      - dry_foods
      - basic_staples

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default